// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization_code.sql

package db

import (
	"context"
	"time"

	"github.com/rizesql/mithras/pkg/idkit"
)

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :one
UPDATE authorization_code
SET
  used_at = now()
WHERE
  code = $1
  AND used_at IS NULL
  AND expires_at > now()
RETURNING
  code,
  user_pk,
  client_id,
  redirect_uri,
  challenge
`

type ConsumeAuthorizationCodeRow struct {
	Code        idkit.AuthorizationCodeID `db:"code"`
	UserPk      int64                     `db:"user_pk"`
	ClientID    string                    `db:"client_id"`
	RedirectUri string                    `db:"redirect_uri"`
	Challenge   string                    `db:"challenge"`
}

// ConsumeAuthorizationCode
//
//	UPDATE authorization_code
//	SET
//	  used_at = now()
//	WHERE
//	  code = $1
//	  AND used_at IS NULL
//	  AND expires_at > now()
//	RETURNING
//	  code,
//	  user_pk,
//	  client_id,
//	  redirect_uri,
//	  challenge
func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, db DBTX, code idkit.AuthorizationCodeID) (ConsumeAuthorizationCodeRow, error) {
	row := db.QueryRow(ctx, consumeAuthorizationCode, code)
	var i ConsumeAuthorizationCodeRow
	err := row.Scan(
		&i.Code,
		&i.UserPk,
		&i.ClientID,
		&i.RedirectUri,
		&i.Challenge,
	)
	return i, err
}

const insertAuthorizationCode = `-- name: InsertAuthorizationCode :one
INSERT INTO authorization_code (
  code,
  user_pk,
  client_id,
  redirect_uri,
  challenge,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING
  code,
  client_id,
  redirect_uri,
  challenge,
  expires_at
`

type InsertAuthorizationCodeParams struct {
	Code        idkit.AuthorizationCodeID `db:"code"`
	UserPk      int64                     `db:"user_pk"`
	ClientID    string                    `db:"client_id"`
	RedirectUri string                    `db:"redirect_uri"`
	Challenge   string                    `db:"challenge"`
	ExpiresAt   time.Time                 `db:"expires_at"`
}

type InsertAuthorizationCodeRow struct {
	Code        idkit.AuthorizationCodeID `db:"code"`
	ClientID    string                    `db:"client_id"`
	RedirectUri string                    `db:"redirect_uri"`
	Challenge   string                    `db:"challenge"`
	ExpiresAt   time.Time                 `db:"expires_at"`
}

// InsertAuthorizationCode
//
//	INSERT INTO authorization_code (
//	  code,
//	  user_pk,
//	  client_id,
//	  redirect_uri,
//	  challenge,
//	  expires_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5,
//	  $6
//	) RETURNING
//	  code,
//	  client_id,
//	  redirect_uri,
//	  challenge,
//	  expires_at
func (q *Queries) InsertAuthorizationCode(ctx context.Context, db DBTX, arg InsertAuthorizationCodeParams) (InsertAuthorizationCodeRow, error) {
	row := db.QueryRow(ctx, insertAuthorizationCode,
		arg.Code,
		arg.UserPk,
		arg.ClientID,
		arg.RedirectUri,
		arg.Challenge,
		arg.ExpiresAt,
	)
	var i InsertAuthorizationCodeRow
	err := row.Scan(
		&i.Code,
		&i.ClientID,
		&i.RedirectUri,
		&i.Challenge,
		&i.ExpiresAt,
	)
	return i, err
}
