// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential_password_insert.sql

package db

import (
	"context"

	"github.com/rizesql/mithras/internal/password"
)

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO "credential_password" (
  user_pk,
  secret
) VALUES  (
  $1,
  $2
)
`

type InsertCredentialParams struct {
	UserPk int64           `db:"user_pk"`
	Secret password.Hashed `db:"secret"`
}

// InsertCredential
//
//	INSERT INTO "credential_password" (
//	  user_pk,
//	  secret
//	) VALUES  (
//	  $1,
//	  $2
//	)
func (q *Queries) InsertCredential(ctx context.Context, db DBTX, arg InsertCredentialParams) error {
	_, err := db.Exec(ctx, insertCredential, arg.UserPk, arg.Secret)
	return err
}

const updateCredentialByUserId = `-- name: UpdateCredentialByUserId :exec
UPDATE "credential_password"
SET
  secret = $1,
  updated_at = now()
WHERE
  user_pk = $2
`

type UpdateCredentialByUserIdParams struct {
	Secret password.Hashed `db:"secret"`
	UserPk int64           `db:"user_pk"`
}

// UpdateCredentialByUserId
//
//	UPDATE "credential_password"
//	SET
//	  secret = $1,
//	  updated_at = now()
//	WHERE
//	  user_pk = $2
func (q *Queries) UpdateCredentialByUserId(ctx context.Context, db DBTX, arg UpdateCredentialByUserIdParams) error {
	_, err := db.Exec(ctx, updateCredentialByUserId, arg.Secret, arg.UserPk)
	return err
}
