// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential_password_insert.sql

package db

import (
	"context"

	"github.com/rizesql/mithras/internal/password"
	"github.com/rizesql/mithras/pkg/idkit"
)

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO "credential_password" (
  user_id,
  secret
) VALUES  (
  $1,
  $2
)
`

type InsertCredentialParams struct {
	UserID idkit.UserID    `db:"user_id"`
	Secret password.Hashed `db:"secret"`
}

// InsertCredential
//
//	INSERT INTO "credential_password" (
//	  user_id,
//	  secret
//	) VALUES  (
//	  $1,
//	  $2
//	)
func (q *Queries) InsertCredential(ctx context.Context, db DBTX, arg InsertCredentialParams) error {
	_, err := db.Exec(ctx, insertCredential, arg.UserID, arg.Secret)
	return err
}
