// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	//InsertCredential
	//
	//  INSERT INTO "credential_password" (
	//    user_id,
	//    secret
	//  ) VALUES  (
	//    $1,
	//    $2
	//  )
	InsertCredential(ctx context.Context, db DBTX, arg InsertCredentialParams) error
	//InsertUser
	//
	//  INSERT INTO "user" (
	//    id,
	//    name,
	//    email
	//  ) values (
	//    $1,
	//    $2,
	//    $3
	//  )
	InsertUser(ctx context.Context, db DBTX, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
