// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/rizesql/mithras/pkg/idkit"
)

type Post struct {
	Pk        int64              `db:"pk"`
	ID        idkit.PostID       `db:"id"`
	Title     pgtype.Text        `db:"title"`
	Body      pgtype.Text        `db:"body"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
}
