// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	//ListPost
	//
	//  SELECT pk, id, title, body, created_at, updated_at
	//  FROM post
	//  WHERE pk > $2
	//  ORDER BY pk ASC
	//  LIMIT $1
	ListPost(ctx context.Context, db DBTX, arg ListPostParams) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
