// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jws.sql

package db

import (
	"context"
	"time"

	"github.com/rizesql/mithras/pkg/idkit"
)

const getActiveJWSKeys = `-- name: GetActiveJWSKeys :many
SELECT
  j.id,
  j.data,
  j.rotates_at,
  j.expires_at
FROM
  "jws" j
WHERE
  j.expires_at > $1
`

type GetActiveJWSKeysRow struct {
	ID        idkit.KeyID `db:"id"`
	Data      []byte      `db:"data"`
	RotatesAt time.Time   `db:"rotates_at"`
	ExpiresAt time.Time   `db:"expires_at"`
}

// GetActiveJWSKeys
//
//	SELECT
//	  j.id,
//	  j.data,
//	  j.rotates_at,
//	  j.expires_at
//	FROM
//	  "jws" j
//	WHERE
//	  j.expires_at > $1
func (q *Queries) GetActiveJWSKeys(ctx context.Context, db DBTX, now time.Time) ([]GetActiveJWSKeysRow, error) {
	rows, err := db.Query(ctx, getActiveJWSKeys, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveJWSKeysRow
	for rows.Next() {
		var i GetActiveJWSKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Data,
			&i.RotatesAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSigningKey = `-- name: GetSigningKey :one
SELECT
  j.id,
  j.data,
  j.rotates_at,
  j.expires_at
FROM
  "jws" j
WHERE
  j.rotates_at > $1
ORDER BY
  j.created_at DESC
LIMIT 1
`

type GetSigningKeyRow struct {
	ID        idkit.KeyID `db:"id"`
	Data      []byte      `db:"data"`
	RotatesAt time.Time   `db:"rotates_at"`
	ExpiresAt time.Time   `db:"expires_at"`
}

// GetSigningKey
//
//	SELECT
//	  j.id,
//	  j.data,
//	  j.rotates_at,
//	  j.expires_at
//	FROM
//	  "jws" j
//	WHERE
//	  j.rotates_at > $1
//	ORDER BY
//	  j.created_at DESC
//	LIMIT 1
func (q *Queries) GetSigningKey(ctx context.Context, db DBTX, now time.Time) (GetSigningKeyRow, error) {
	row := db.QueryRow(ctx, getSigningKey, now)
	var i GetSigningKeyRow
	err := row.Scan(
		&i.ID,
		&i.Data,
		&i.RotatesAt,
		&i.ExpiresAt,
	)
	return i, err
}

const insertJWSKey = `-- name: InsertJWSKey :exec
INSERT INTO "jws" (
  id,
  data,
  rotates_at,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4
)
`

type InsertJWSKeyParams struct {
	ID        idkit.KeyID `db:"id"`
	Data      []byte      `db:"data"`
	RotatesAt time.Time   `db:"rotates_at"`
	ExpiresAt time.Time   `db:"expires_at"`
}

// InsertJWSKey
//
//	INSERT INTO "jws" (
//	  id,
//	  data,
//	  rotates_at,
//	  expires_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4
//	)
func (q *Queries) InsertJWSKey(ctx context.Context, db DBTX, arg InsertJWSKeyParams) error {
	_, err := db.Exec(ctx, insertJWSKey,
		arg.ID,
		arg.Data,
		arg.RotatesAt,
		arg.ExpiresAt,
	)
	return err
}

const pruneJWS = `-- name: PruneJWS :exec
DELETE FROM "jws"
WHERE expires_at < $1
`

// PruneJWS
//
//	DELETE FROM "jws"
//	WHERE expires_at < $1
func (q *Queries) PruneJWS(ctx context.Context, db DBTX, now time.Time) error {
	_, err := db.Exec(ctx, pruneJWS, now)
	return err
}
