// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_history.sql

package db

import (
	"context"

	"github.com/rizesql/mithras/internal/password"
)

const getRecentPasswordHashes = `-- name: GetRecentPasswordHashes :many
SELECT
  secret
FROM
  "password_history"
WHERE
  user_pk = $1
ORDER BY
  created_at DESC
LIMIT $2
`

type GetRecentPasswordHashesParams struct {
	UserPk int64 `db:"user_pk"`
	Limit  int32 `db:"limit"`
}

// GetRecentPasswordHashes
//
//	SELECT
//	  secret
//	FROM
//	  "password_history"
//	WHERE
//	  user_pk = $1
//	ORDER BY
//	  created_at DESC
//	LIMIT $2
func (q *Queries) GetRecentPasswordHashes(ctx context.Context, db DBTX, arg GetRecentPasswordHashesParams) ([]password.Hashed, error) {
	rows, err := db.Query(ctx, getRecentPasswordHashes, arg.UserPk, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []password.Hashed
	for rows.Next() {
		var secret password.Hashed
		if err := rows.Scan(&secret); err != nil {
			return nil, err
		}
		items = append(items, secret)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPasswordHistory = `-- name: InsertPasswordHistory :exec
INSERT INTO "password_history" (user_pk, secret)
VALUES ($1, $2)
`

type InsertPasswordHistoryParams struct {
	UserPk int64           `db:"user_pk"`
	Secret password.Hashed `db:"secret"`
}

// InsertPasswordHistory
//
//	INSERT INTO "password_history" (user_pk, secret)
//	VALUES ($1, $2)
func (q *Queries) InsertPasswordHistory(ctx context.Context, db DBTX, arg InsertPasswordHistoryParams) error {
	_, err := db.Exec(ctx, insertPasswordHistory, arg.UserPk, arg.Secret)
	return err
}
