// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const passwordResetGetActive = `-- name: PasswordResetGetActive :one
SELECT
  pk,
  id,
  user_pk,
  token_hash,
  expires_at
FROM
  "password_reset"
WHERE
  id = $1
  AND used_at IS NULL
  AND expires_at > now()
LIMIT 1
`

type PasswordResetGetActiveRow struct {
	Pk        int64       `db:"pk"`
	ID        interface{} `db:"id"`
	UserPk    int64       `db:"user_pk"`
	TokenHash []byte      `db:"token_hash"`
	ExpiresAt time.Time   `db:"expires_at"`
}

// PasswordResetGetActive
//
//	SELECT
//	  pk,
//	  id,
//	  user_pk,
//	  token_hash,
//	  expires_at
//	FROM
//	  "password_reset"
//	WHERE
//	  id = $1
//	  AND used_at IS NULL
//	  AND expires_at > now()
//	LIMIT 1
func (q *Queries) PasswordResetGetActive(ctx context.Context, db DBTX, id interface{}) (PasswordResetGetActiveRow, error) {
	row := db.QueryRow(ctx, passwordResetGetActive, id)
	var i PasswordResetGetActiveRow
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.UserPk,
		&i.TokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const passwordResetInsert = `-- name: PasswordResetInsert :one
INSERT INTO "password_reset" (
  id,
  user_pk,
  token_hash,
  user_agent,
  ip_addr,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING pk
`

type PasswordResetInsertParams struct {
	ID        interface{} `db:"id"`
	UserPk    int64       `db:"user_pk"`
	TokenHash []byte      `db:"token_hash"`
	UserAgent *string     `db:"user_agent"`
	IpAddr    netip.Addr  `db:"ip_addr"`
	ExpiresAt time.Time   `db:"expires_at"`
}

// PasswordResetInsert
//
//	INSERT INTO "password_reset" (
//	  id,
//	  user_pk,
//	  token_hash,
//	  user_agent,
//	  ip_addr,
//	  expires_at
//	) VALUES (
//	  $1, $2, $3, $4, $5, $6
//	) RETURNING pk
func (q *Queries) PasswordResetInsert(ctx context.Context, db DBTX, arg PasswordResetInsertParams) (int64, error) {
	row := db.QueryRow(ctx, passwordResetInsert,
		arg.ID,
		arg.UserPk,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddr,
		arg.ExpiresAt,
	)
	var pk int64
	err := row.Scan(&pk)
	return pk, err
}

const passwordResetInvalidateSiblings = `-- name: PasswordResetInvalidateSiblings :exec
UPDATE "password_reset"
SET used_at = now()
WHERE user_pk = $1 AND used_at IS NULL AND pk != $2
`

type PasswordResetInvalidateSiblingsParams struct {
	UserPk int64 `db:"user_pk"`
	Pk     int64 `db:"pk"`
}

// PasswordResetInvalidateSiblings
//
//	UPDATE "password_reset"
//	SET used_at = now()
//	WHERE user_pk = $1 AND used_at IS NULL AND pk != $2
func (q *Queries) PasswordResetInvalidateSiblings(ctx context.Context, db DBTX, arg PasswordResetInvalidateSiblingsParams) error {
	_, err := db.Exec(ctx, passwordResetInvalidateSiblings, arg.UserPk, arg.Pk)
	return err
}

const passwordResetMarkUsed = `-- name: PasswordResetMarkUsed :exec
UPDATE "password_reset"
SET used_at = now()
WHERE pk = $1
`

// PasswordResetMarkUsed
//
//	UPDATE "password_reset"
//	SET used_at = now()
//	WHERE pk = $1
func (q *Queries) PasswordResetMarkUsed(ctx context.Context, db DBTX, pk int64) error {
	_, err := db.Exec(ctx, passwordResetMarkUsed, pk)
	return err
}
