// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post_list.sql

package db

import (
	"context"
)

const listPost = `-- name: ListPost :many
SELECT pk, id, title, body, created_at, updated_at
FROM post
WHERE pk > $2
ORDER BY pk ASC
LIMIT $1
`

type ListPostParams struct {
	Limit            int32 `db:"limit"`
	PaginationCursor int64 `db:"pagination_cursor"`
}

// ListPost
//
//	SELECT pk, id, title, body, created_at, updated_at
//	FROM post
//	WHERE pk > $2
//	ORDER BY pk ASC
//	LIMIT $1
func (q *Queries) ListPost(ctx context.Context, db DBTX, arg ListPostParams) ([]Post, error) {
	rows, err := db.Query(ctx, listPost, arg.Limit, arg.PaginationCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
