// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_revoke_of_user.sql

package db

import (
	"context"
	"time"
)

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE "session"
SET
  revoked_at = $1
WHERE
  user_pk = $2
AND
  revoked_at IS NULL
`

type RevokeUserSessionsParams struct {
	Now    *time.Time `db:"now"`
	UserPk int64      `db:"user_pk"`
}

// RevokeUserSessions
//
//	UPDATE "session"
//	SET
//	  revoked_at = $1
//	WHERE
//	  user_pk = $2
//	AND
//	  revoked_at IS NULL
func (q *Queries) RevokeUserSessions(ctx context.Context, db DBTX, arg RevokeUserSessionsParams) error {
	_, err := db.Exec(ctx, revokeUserSessions, arg.Now, arg.UserPk)
	return err
}
