// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_revoke.sql

package db

import (
	"context"
)

const revokeSession = `-- name: RevokeSession :execrows
UPDATE "session"
SET revoked_at = now()
WHERE pk = $1 AND revoked_at IS NULL
`

// RevokeSession
//
//	UPDATE "session"
//	SET revoked_at = now()
//	WHERE pk = $1 AND revoked_at IS NULL
func (q *Queries) RevokeSession(ctx context.Context, db DBTX, pk int64) (int64, error) {
	result, err := db.Exec(ctx, revokeSession, pk)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
