// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_insert.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/rizesql/mithras/pkg/idkit"
)

const insertSession = `-- name: InsertSession :exec
INSERT INTO "session" (
  id,
  user_pk,
  token_hash,
  user_agent,
  ip_addr,
  expires_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
`

type InsertSessionParams struct {
	ID        idkit.SessionID `db:"id"`
	UserPk    int64           `db:"user_pk"`
	TokenHash []byte          `db:"token_hash"`
	UserAgent *string         `db:"user_agent"`
	IpAddr    netip.Addr      `db:"ip_addr"`
	ExpiresAt time.Time       `db:"expires_at"`
}

// InsertSession
//
//	INSERT INTO "session" (
//	  id,
//	  user_pk,
//	  token_hash,
//	  user_agent,
//	  ip_addr,
//	  expires_at
//	) VALUES (
//	  $1,
//	  $2,
//	  $3,
//	  $4,
//	  $5,
//	  $6
//	)
func (q *Queries) InsertSession(ctx context.Context, db DBTX, arg InsertSessionParams) error {
	_, err := db.Exec(ctx, insertSession,
		arg.ID,
		arg.UserPk,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddr,
		arg.ExpiresAt,
	)
	return err
}
