// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_get_by_token_hash.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/rizesql/mithras/pkg/idkit"
)

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
  s.pk,
  s.id,
  s.user_pk,
  s.expires_at,
  s.revoked_at,
  s.user_agent,
  s.ip_addr,
  u.id AS user_id,
  u.status AS user_status,
  u.locked_until AS user_locked_until
FROM
  "session" s
JOIN
  "user" u ON s.user_pk = u.pk
WHERE
  s.token_hash = $1
LIMIT 1
`

type GetSessionByTokenHashRow struct {
	Pk              int64           `db:"pk"`
	ID              idkit.SessionID `db:"id"`
	UserPk          int64           `db:"user_pk"`
	ExpiresAt       time.Time       `db:"expires_at"`
	RevokedAt       *time.Time      `db:"revoked_at"`
	UserAgent       *string         `db:"user_agent"`
	IpAddr          netip.Addr      `db:"ip_addr"`
	UserID          idkit.UserID    `db:"user_id"`
	UserStatus      UserStatus      `db:"user_status"`
	UserLockedUntil *time.Time      `db:"user_locked_until"`
}

// GetSessionByTokenHash
//
//	SELECT
//	  s.pk,
//	  s.id,
//	  s.user_pk,
//	  s.expires_at,
//	  s.revoked_at,
//	  s.user_agent,
//	  s.ip_addr,
//	  u.id AS user_id,
//	  u.status AS user_status,
//	  u.locked_until AS user_locked_until
//	FROM
//	  "session" s
//	JOIN
//	  "user" u ON s.user_pk = u.pk
//	WHERE
//	  s.token_hash = $1
//	LIMIT 1
func (q *Queries) GetSessionByTokenHash(ctx context.Context, db DBTX, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.UserPk,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.IpAddr,
		&i.UserID,
		&i.UserStatus,
		&i.UserLockedUntil,
	)
	return i, err
}
