// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_insert.sql

package db

import (
	"context"

	"github.com/rizesql/mithras/internal/email"
	"github.com/rizesql/mithras/pkg/idkit"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" (
  id,
  name,
  email
) values (
  $1,
  $2,
  $3
)
RETURNING pk
`

type InsertUserParams struct {
	ID    idkit.UserID  `db:"id"`
	Name  string        `db:"name"`
	Email email.Address `db:"email"`
}

// InsertUser
//
//	INSERT INTO "user" (
//	  id,
//	  name,
//	  email
//	) values (
//	  $1,
//	  $2,
//	  $3
//	)
//	RETURNING pk
func (q *Queries) InsertUser(ctx context.Context, db DBTX, arg InsertUserParams) (int64, error) {
	row := db.QueryRow(ctx, insertUser, arg.ID, arg.Name, arg.Email)
	var pk int64
	err := row.Scan(&pk)
	return pk, err
}
