// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_insert.sql

package db

import (
	"context"

	"github.com/rizesql/mithras/internal/email"
	"github.com/rizesql/mithras/pkg/idkit"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO "user" (
  id,
  name,
  email
) values (
  $1,
  $2,
  $3
)
`

type InsertUserParams struct {
	ID    idkit.UserID  `db:"id"`
	Name  string        `db:"name"`
	Email email.Address `db:"email"`
}

// InsertUser
//
//	INSERT INTO "user" (
//	  id,
//	  name,
//	  email
//	) values (
//	  $1,
//	  $2,
//	  $3
//	)
func (q *Queries) InsertUser(ctx context.Context, db DBTX, arg InsertUserParams) error {
	_, err := db.Exec(ctx, insertUser, arg.ID, arg.Name, arg.Email)
	return err
}
