// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_get_with_password.sql

package db

import (
	"context"
	"time"

	"github.com/rizesql/mithras/internal/email"
	"github.com/rizesql/mithras/internal/password"
	"github.com/rizesql/mithras/pkg/idkit"
)

const getUserWithPassword = `-- name: GetUserWithPassword :one
SELECT
  u.pk,
  u.id,
  u.status,
  u.failed_attempts,
  u.locked_until,
  cp.secret
FROM
  "user" u
JOIN
  "credential_password" cp ON u.pk = cp.user_pk
WHERE
  u.email = $1
LIMIT 1
`

type GetUserWithPasswordRow struct {
	Pk             int64           `db:"pk"`
	ID             idkit.UserID    `db:"id"`
	Status         UserStatus      `db:"status"`
	FailedAttempts int32           `db:"failed_attempts"`
	LockedUntil    *time.Time      `db:"locked_until"`
	Secret         password.Hashed `db:"secret"`
}

// GetUserWithPassword
//
//	SELECT
//	  u.pk,
//	  u.id,
//	  u.status,
//	  u.failed_attempts,
//	  u.locked_until,
//	  cp.secret
//	FROM
//	  "user" u
//	JOIN
//	  "credential_password" cp ON u.pk = cp.user_pk
//	WHERE
//	  u.email = $1
//	LIMIT 1
func (q *Queries) GetUserWithPassword(ctx context.Context, db DBTX, argEmail email.Address) (GetUserWithPasswordRow, error) {
	row := db.QueryRow(ctx, getUserWithPassword, argEmail)
	var i GetUserWithPasswordRow
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.Secret,
	)
	return i, err
}
