// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_status.sql

package db

import (
	"context"
	"time"
)

const lockAccount = `-- name: LockAccount :exec
UPDATE "user"
SET
  status = 'locked',
  locked_until = $1,
  updated_at = now()
WHERE
  pk = $2
`

type LockAccountParams struct {
	LockedUntil *time.Time `db:"locked_until"`
	UserPk      int64      `db:"user_pk"`
}

// LockAccount
//
//	UPDATE "user"
//	SET
//	  status = 'locked',
//	  locked_until = $1,
//	  updated_at = now()
//	WHERE
//	  pk = $2
func (q *Queries) LockAccount(ctx context.Context, db DBTX, arg LockAccountParams) error {
	_, err := db.Exec(ctx, lockAccount, arg.LockedUntil, arg.UserPk)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE "user"
SET
  failed_attempts = failed_attempts + 1,
  updated_at = now()
WHERE
  pk = $1
`

// RecordLoginFailure
//
//	UPDATE "user"
//	SET
//	  failed_attempts = failed_attempts + 1,
//	  updated_at = now()
//	WHERE
//	  pk = $1
func (q *Queries) RecordLoginFailure(ctx context.Context, db DBTX, userPk int64) error {
	_, err := db.Exec(ctx, recordLoginFailure, userPk)
	return err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE "user"
SET
  failed_attempts = 0,
  locked_until = NULL,
  status = 'active',
  last_login_at = now(),
  updated_at = now()
WHERE
  pk = $1
`

// RecordLoginSuccess
//
//	UPDATE "user"
//	SET
//	  failed_attempts = 0,
//	  locked_until = NULL,
//	  status = 'active',
//	  last_login_at = now(),
//	  updated_at = now()
//	WHERE
//	  pk = $1
func (q *Queries) RecordLoginSuccess(ctx context.Context, db DBTX, userPk int64) error {
	_, err := db.Exec(ctx, recordLoginSuccess, userPk)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE "user"
SET
  status = $1,
  locked_until = CASE WHEN $1 = 'active'::user_status THEN NULL ELSE locked_until END,
  failed_attempts = CASE WHEN $1 = 'active'::user_status THEN 0 ELSE failed_attempts END,
  updated_at = now()
WHERE
  pk = $2
`

type UpdateUserStatusParams struct {
	Status UserStatus `db:"status"`
	UserPk int64      `db:"user_pk"`
}

// UpdateUserStatus
//
//	UPDATE "user"
//	SET
//	  status = $1,
//	  locked_until = CASE WHEN $1 = 'active'::user_status THEN NULL ELSE locked_until END,
//	  failed_attempts = CASE WHEN $1 = 'active'::user_status THEN 0 ELSE failed_attempts END,
//	  updated_at = now()
//	WHERE
//	  pk = $2
func (q *Queries) UpdateUserStatus(ctx context.Context, db DBTX, arg UpdateUserStatusParams) error {
	_, err := db.Exec(ctx, updateUserStatus, arg.Status, arg.UserPk)
	return err
}
