// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRole = `-- name: AssignRole :exec
INSERT INTO "user_role" (user_pk, role_pk, granted_by)
VALUES ($1, (SELECT pk FROM "role" WHERE name = $2), $3)
`

type AssignRoleParams struct {
	UserPk    int64       `db:"user_pk"`
	Name      string      `db:"name"`
	GrantedBy pgtype.Int8 `db:"granted_by"`
}

// AssignRole
//
//	INSERT INTO "user_role" (user_pk, role_pk, granted_by)
//	VALUES ($1, (SELECT pk FROM "role" WHERE name = $2), $3)
func (q *Queries) AssignRole(ctx context.Context, db DBTX, arg AssignRoleParams) error {
	_, err := db.Exec(ctx, assignRole, arg.UserPk, arg.Name, arg.GrantedBy)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT
  r.name
FROM
  "role" r
JOIN
  "user_role" ur ON r.pk = ur.role_pk
WHERE
  ur.user_pk = $1
`

// GetUserRoles
//
//	SELECT
//	  r.name
//	FROM
//	  "role" r
//	JOIN
//	  "user_role" ur ON r.pk = ur.role_pk
//	WHERE
//	  ur.user_pk = $1
func (q *Queries) GetUserRoles(ctx context.Context, db DBTX, userPk int64) ([]string, error) {
	rows, err := db.Query(ctx, getUserRoles, userPk)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
