// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_get_by_pk.sql

package db

import (
	"context"
)

const getUserByPk = `-- name: GetUserByPk :one
SELECT pk, id, name, email, status, failed_attempts, locked_until, last_login_at, created_at, updated_at FROM "user"
WHERE pk = $1 LIMIT 1
`

// GetUserByPk
//
//	SELECT pk, id, name, email, status, failed_attempts, locked_until, last_login_at, created_at, updated_at FROM "user"
//	WHERE pk = $1 LIMIT 1
func (q *Queries) GetUserByPk(ctx context.Context, db DBTX, pk int64) (User, error) {
	row := db.QueryRow(ctx, getUserByPk, pk)
	var i User
	err := row.Scan(
		&i.Pk,
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
