// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_list.sql

package db

import (
	"context"
)

const listUsers = `-- name: ListUsers :many
SELECT
  pk, id, name, email, created_at, updated_at
FROM
  "user"
WHERE
  pk > $2
ORDER BY
  pk ASC
LIMIT
  $1
`

type ListUsersParams struct {
	Limit            int32 `db:"limit"`
	PaginationCursor int64 `db:"pagination_cursor"`
}

// ListUsers
//
//	SELECT
//	  pk, id, name, email, created_at, updated_at
//	FROM
//	  "user"
//	WHERE
//	  pk > $2
//	ORDER BY
//	  pk ASC
//	LIMIT
//	  $1
func (q *Queries) ListUsers(ctx context.Context, db DBTX, arg ListUsersParams) ([]User, error) {
	rows, err := db.Query(ctx, listUsers, arg.Limit, arg.PaginationCursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Pk,
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
