//go:build ignore

package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi/bundler"
	"github.com/pb33f/libopenapi/datamodel"
)

func main() {
	input := flag.String("input", "spec/openapi.yaml", "Input OpenAPI file")
	output := flag.String("output", "generated_openapi.yaml", "Output bundled OpenAPI file")

	data, err := os.ReadFile(*input)
	if err != nil {
		log.Fatalf("Failed to read input file: %v", err)
	}

	config := datamodel.NewDocumentConfiguration()

	config.BasePath = filepath.Dir(*input)
	config.ExtractRefsSequentially = true
	config.AllowFileReferences = true

	document, err := libopenapi.NewDocumentWithConfiguration(data, config)
	if err != nil {
		log.Fatalf("Failed to parse OpenAPI document: %v", err)
	}

	model, err := document.BuildV3Model()
	if err != nil {
		log.Fatalf("Failed to build v3 model: %v", err)
	}

	log.Printf("Model built successfully using version %s", model.Model.Version)

	// 4. Bundle the document (this natively handles all the $ref inlining you were doing)
	bundle, err := bundler.BundleDocumentComposed(&model.Model, nil)
	if err != nil {
		log.Fatalf("Failed to bundle document: %v", err)
	}

	header := fmt.Appendf(nil, "# Code generated by generate_bundle.go; DO NOT EDIT.\n# Source: %s\n\n", *input)
	generated := append(header, bundle...)

	if err := os.WriteFile(*output, generated, 0644); err != nil {
		log.Fatalf("Failed to write output file %s: %v", *output, err)
	}

	fmt.Printf("Successfully bundled OpenAPI spec to %s\n", *output)
}

// import (
// 	"flag"
// 	"fmt"
// 	"log"
// 	"os"
// 	"path/filepath"
// 	"strings"

// 	"github.com/pb33f/libopenapi"
// 	"github.com/pb33f/libopenapi/bundler"
// 	"github.com/pb33f/libopenapi/datamodel"
// 	"gopkg.in/yaml.v3"
// )

// var (
// 	input  = flag.String("input", "spec/openapi.yaml", "Input OpenAPI file")
// 	output = flag.String("output", "generated_openapi.yaml", "Output bundled OpenAPI file")
// )

// func main() {
// 	flag.Parse()

// 	preprocessedSpec, err := preprocessPaths(*input)
// 	if err != nil {
// 		log.Fatalf("Failed to preprocess paths: %v", err)
// 	}

// 	config := datamodel.NewDocumentConfiguration()
// 	config.BasePath = "."
// 	config.ExtractRefsSequentially = true

// 	document, err := libopenapi.NewDocumentWithConfiguration(preprocessedSpec, config)
// 	if err != nil {
// 		log.Fatalf("Failed to parse OpenAPI document: %v", err)
// 	}

// 	v3Model, err := document.BuildV3Model()
// 	if err != nil {
// 		log.Fatalf("Failed to build v3 model: %v", err)
// 	}

// 	log.Printf("Model built successfully using version %s", v3Model.Model.Version)

// 	bundledBytes, err := bundler.BundleDocumentComposed(&v3Model.Model, nil)
// 	if err != nil {
// 		log.Fatalf("Failed to bundle document: %v", err)
// 	}

// 	header := fmt.Sprintf(`# Code generated by generate_bundle.go; DO NOT EDIT.
// # Source: %s

// `, *input)

// 	finalContent := append([]byte(header), bundledBytes...)

// 	err = os.WriteFile(*output, finalContent, 0644)
// 	if err != nil {
// 		log.Fatalf("Failed to write output file %s: %v", *output, err)
// 	}

// 	fmt.Printf("Successfully bundled OpenAPI spec to %s\n", *output)
// }

// func preprocessPaths(inputFile string) ([]byte, error) {
// 	data, err := os.ReadFile(inputFile)
// 	if err != nil {
// 		return nil, fmt.Errorf("failed to read input file: %w", err)
// 	}

// 	var spec map[string]any
// 	if err := yaml.Unmarshal(data, &spec); err != nil {
// 		return nil, fmt.Errorf("failed to parse yaml: %w", err)
// 	}

// 	// Process paths to inline $refs
// 	if paths, ok := spec["paths"].(map[string]any); ok {
// 		newPaths := make(map[string]any)

// 		for pathKey, pathValue := range paths {
// 			pathMap, ok := pathValue.(map[string]any)
// 			if !ok {
// 				newPaths[pathKey] = pathValue
// 				continue
// 			}

// 			ref, ok := pathMap["$ref"].(string)
// 			if !ok {
// 				newPaths[pathKey] = pathValue
// 				continue
// 			}

// 			refData, err := os.ReadFile(ref)
// 			if err != nil {
// 				return nil, fmt.Errorf("failed to read path ref %s: %w", ref, err)
// 			}

// 			var pathContent any
// 			if err := yaml.Unmarshal(refData, &pathContent); err != nil {
// 				return nil, fmt.Errorf("failed to parse path ref %s: %w", ref, err)
// 			}

// 			refDir := filepath.Dir(ref)
// 			pathContent = fixRelativeRefs(pathContent, refDir)

// 			newPaths[pathKey] = pathContent
// 		}

// 		spec["paths"] = newPaths
// 	}

// 	preprocessedYAML, err := yaml.Marshal(spec)
// 	if err != nil {
// 		return nil, fmt.Errorf("failed to marshal preprocessed spec: %w", err)
// 	}

// 	return preprocessedYAML, nil
// }

// // fixRelativeRefs recursively fixes relative $refs in the data structure
// func fixRelativeRefs(data any, baseDir string) any {
// 	switch v := data.(type) {
// 	case map[string]any:
// 		result := make(map[string]any)
// 		for key, value := range v {
// 			if key != "$ref" {
// 				result[key] = fixRelativeRefs(value, baseDir)
// 				continue
// 			}

// 			refStr, ok := value.(string)
// 			if !ok {
// 				result[key] = value
// 				continue
// 			}

// 			if !strings.HasPrefix(refStr, "#/") && !strings.HasPrefix(refStr, "http") && strings.HasSuffix(refStr, ".yaml") {
// 				newRef := filepath.Join(baseDir, refStr)
// 				newRef = filepath.Clean(newRef)
// 				if !strings.HasPrefix(newRef, "./") && !strings.HasPrefix(newRef, "../") {
// 					newRef = "./" + newRef
// 				}

// 				result[key] = newRef
// 				continue
// 			}

// 			result[key] = value
// 		}

// 		return result
// 	case []any:
// 		result := make([]any, len(v))
// 		for i, item := range v {
// 			result[i] = fixRelativeRefs(item, baseDir)
// 		}
// 		return result
// 	default:
// 		return v
// 	}
// }
