// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// FieldError A single field-level validation error.
//
// Extension to RFC 7807 Problem Details providing granular information about
// which field failed validation and why. Only used in `validation_error_response`
// bodies — never in authentication or authorization error responses.
type FieldError struct {
	// Code Machine-readable code for this validation failure.
	Code *string `json:"code,omitempty"`

	// Hint Suggested fix or expected value format.
	Hint *string `json:"hint,omitempty"`

	// InvalidValue The invalid value that was provided, if safe to echo back.
	InvalidValue *string `json:"invalid_value,omitempty"`

	// Message Human-readable explanation of the validation failure.
	Message string `json:"message"`

	// Path JSON path to the invalid field, prefixed with its location.
	// Examples: `body.email`, `query.page`, `header.authorization`.
	Path string `json:"path"`
}

// Problem RFC 7807 Problem Details for HTTP APIs.
//
// Provides machine-readable error details in HTTP responses. The `request_id`
// field is an extension to the base RFC 7807 format — it is always present
// and matches the `X-Request-Id` response header, making the error body
// fully self-contained for debugging without requiring access to response
// headers.
//
// See https://tools.ietf.org/html/rfc7807.
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence. May vary between occurrences
	// of the same problem type.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence. Typically the request path.
	Instance *string `json:"instance,omitempty"`

	// RequestId Unique identifier for the request that produced this error. Matches the `X-Request-Id`
	// response header. Include this value when reporting issues or investigating security events.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence of the problem.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type. Does not change between
	// occurrences of the same problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. Dereference for human-readable documentation.
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// V2RegisterRequest defines model for V2RegisterRequest.
type V2RegisterRequest struct {
	// Email The user's email address.
	Email openapi_types.Email `json:"email"`

	// Name The user's preferred name.
	Name string `json:"name"`

	// Password The user's chosen password. Must be at least 8 characters long and contain
	// at least one uppercase letter, one lowercase letter, one digit, and one special character.
	Password string `json:"password"`
}

// V2RegisterResponse defines model for V2RegisterResponse.
type V2RegisterResponse struct {
	// Id The unique identifier for the created user.
	Id string `json:"id"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError struct {
	// Detail Human-readable explanation specific to this occurrence. May vary between occurrences
	// of the same problem type.
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level validation errors. Each entry identifies the
	// invalid field and explains the failure.
	//
	// **Security note:** This array is only returned for structural
	// validation failures (malformed JSON, missing required fields,
	// type mismatches). It is never returned for authentication
	// failures — auth errors always use the base `problem` type
	// with a single generic message to prevent user enumeration.
	Errors []FieldError `json:"errors"`

	// Instance URI reference identifying the specific occurrence. Typically the request path.
	Instance *string `json:"instance,omitempty"`

	// RequestId Unique identifier for the request that produced this error. Matches the `X-Request-Id`
	// response header. Include this value when reporting issues or investigating security events.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence of the problem.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type. Does not change between
	// occurrences of the same problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. Dereference for human-readable documentation.
	Type string `json:"type"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError struct {
	// Code Optional machine-readable error code for internal tracking
	Code *string `json:"code,omitempty"`

	// Detail Human-readable explanation specific to this occurrence. May vary between occurrences
	// of the same problem type.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence. Typically the request path.
	Instance *string `json:"instance,omitempty"`

	// RequestId Unique identifier for the request that produced this error. Matches the `X-Request-Id`
	// response header. Include this value when reporting issues or investigating security events.
	RequestId string `json:"request_id"`

	// Status HTTP status code for this occurrence of the problem.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type. Does not change between
	// occurrences of the same problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. Dereference for human-readable documentation.
	Type string `json:"type"`
}

// RateLimitError defines model for RateLimitError.
type RateLimitError struct {
	// Detail Human-readable explanation specific to this occurrence. May vary between occurrences
	// of the same problem type.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence. Typically the request path.
	Instance *string `json:"instance,omitempty"`

	// RequestId Unique identifier for the request that produced this error. Matches the `X-Request-Id`
	// response header. Include this value when reporting issues or investigating security events.
	RequestId string `json:"request_id"`

	// RetryAfter RFC3339 timestamp indicating when the rate limit window resets
	// and the client may retry. Matches the `Retry-After` response
	// header value.
	RetryAfter time.Time `json:"retry_after"`

	// Status HTTP status code for this occurrence of the problem.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem type. Does not change between
	// occurrences of the same problem type.
	Title string `json:"title"`

	// Type URI reference identifying the problem type. Dereference for human-readable documentation.
	Type string `json:"type"`
}

// V2RegisterJSONRequestBody defines body for V2Register for application/json ContentType.
type V2RegisterJSONRequestBody = V2RegisterRequest

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["request_id"]; found {
		err = json.Unmarshal(raw, &a.RequestId)
		if err != nil {
			return fmt.Errorf("error reading 'request_id': %w", err)
		}
		delete(object, "request_id")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["request_id"], err = json.Marshal(a.RequestId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'request_id': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
