name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'push' ||
      !startsWith(github.event.head_commit.message, 'Merge pull request #')

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - run: nix flake check --print-build-logs
      - run: nix develop --command go test -race ./...
      - run: nix develop --command go tool golangci-lint run ./...
      - run: nix develop --command go tool gosec ./...
      - run: nix develop --command go tool govulncheck ./...
