name: CI

on:
  pull_request:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: GolangCI-lint
        run: nix develop --command golangci-lint run ./...

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Check formatting
        run: nix develop --command gofmt -l .

  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - run: nix flake check --print-build-logs

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Run Standard Tests
        run: nix develop --command go test -v ./...

  test-race:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-nix

      - name: Run Race Detector
        run: nix develop --command go test -race -v -short ./...
